#files under this directory that are of a supported file type will be made available as endpoints
RootDirectory = 
Port = 4221
#max request buffer size in bytes, recommend not exceeding 1MB
MaxRequestBufferSize = 16384
